//----------------------
// <auto-generated>
//     Generated using the NSwag toolchain v13.20.0.0 (NJsonSchema v11.0.0.0 (Newtonsoft.Json v13.0.0.0)) (http://NSwag.org)
// </auto-generated>
//----------------------

/* tslint:disable */
/* eslint-disable */
// ReSharper disable InconsistentNaming
import * as Types from '../axios-client';
import type { AxiosRequestConfig, AxiosResponse, CancelToken } from 'axios';

import { throwException, isAxiosError } from '../axios-client';
import { getAxios, getBaseUrl } from './helpers';

export function save(body: Types.ContactRequestDto, config?: AxiosRequestConfig | undefined): Promise<Types.Anonymous5> {
    let url_ = getBaseUrl() + "/contact/createContact";
      url_ = url_.replace(/[?&]$/, "");

    const content_ = JSON.stringify(body);

    let options_: AxiosRequestConfig = {
        ..._requestConfigSave,
        ...config,
        data: content_,
        method: "POST",
        url: url_,
        headers: {
            ..._requestConfigSave?.headers,
            "Content-Type": "application/json",
            "Accept": "application/json",
            ...config?.headers,
        }
    };

    return getAxios().request(options_).catch((_error: any) => {
        if (isAxiosError(_error) && _error.response) {
            return _error.response;
        } else {
            throw _error;
        }
    }).then((_response: AxiosResponse) => {
        return processSave(_response);
    });
}

function processSave(response: AxiosResponse): Promise<Types.Anonymous5> {
    const status = response.status;
    let _headers: any = {};
    if (response.headers && typeof response.headers === "object") {
        for (let k in response.headers) {
            if (response.headers.hasOwnProperty(k)) {
                _headers[k] = response.headers[k];
            }
        }
    }
    if (status === 200) {
        const _responseText = response.data;
        let result200: any = null;
        let resultData200  = _responseText;
            result200 = resultData200 !== undefined ? resultData200 : <any>null;
    
        return Promise.resolve<Types.Anonymous5>(result200);

    } else if (status === 201) {
        const _responseText = response.data;
        return throwException("A server side error occurred.", status, _responseText, _headers);

    } else if (status !== 200 && status !== 204) {
        const _responseText = response.data;
        return throwException("An unexpected server error occurred.", status, _responseText, _headers);
    }
    return Promise.resolve<Types.Anonymous5>(null as any);
}

export function getContacts(id: string, config?: AxiosRequestConfig | undefined): Promise<Types.Anonymous6> {
    let url_ = getBaseUrl() + "/contact/getContactsByInspectionId/{id}";
    if (id === undefined || id === null)
      throw new Error("The parameter 'id' must be defined.");
    url_ = url_.replace("{id}", encodeURIComponent("" + id));
      url_ = url_.replace(/[?&]$/, "");

    let options_: AxiosRequestConfig = {
        ..._requestConfigGetContacts,
        ...config,
        method: "GET",
        url: url_,
        headers: {
            ..._requestConfigGetContacts?.headers,
            "Accept": "application/json",
            ...config?.headers,
        }
    };

    return getAxios().request(options_).catch((_error: any) => {
        if (isAxiosError(_error) && _error.response) {
            return _error.response;
        } else {
            throw _error;
        }
    }).then((_response: AxiosResponse) => {
        return processGetContacts(_response);
    });
}

function processGetContacts(response: AxiosResponse): Promise<Types.Anonymous6> {
    const status = response.status;
    let _headers: any = {};
    if (response.headers && typeof response.headers === "object") {
        for (let k in response.headers) {
            if (response.headers.hasOwnProperty(k)) {
                _headers[k] = response.headers[k];
            }
        }
    }
    if (status === 200) {
        const _responseText = response.data;
        let result200: any = null;
        let resultData200  = _responseText;
            result200 = resultData200 !== undefined ? resultData200 : <any>null;
    
        return Promise.resolve<Types.Anonymous6>(result200);

    } else if (status !== 200 && status !== 204) {
        const _responseText = response.data;
        return throwException("An unexpected server error occurred.", status, _responseText, _headers);
    }
    return Promise.resolve<Types.Anonymous6>(null as any);
}
let _requestConfigSave: Partial<AxiosRequestConfig> | null;
export function getSaveRequestConfig() {
  return _requestConfigSave;
}
export function setSaveRequestConfig(value: Partial<AxiosRequestConfig>) {
  _requestConfigSave = value;
}
export function patchSaveRequestConfig(patch: (value: Partial<AxiosRequestConfig>) => Partial<AxiosRequestConfig>) {
  _requestConfigSave = patch(_requestConfigSave ?? {});
}

let _requestConfigGetContacts: Partial<AxiosRequestConfig> | null;
export function getGetContactsRequestConfig() {
  return _requestConfigGetContacts;
}
export function setGetContactsRequestConfig(value: Partial<AxiosRequestConfig>) {
  _requestConfigGetContacts = value;
}
export function patchGetContactsRequestConfig(patch: (value: Partial<AxiosRequestConfig>) => Partial<AxiosRequestConfig>) {
  _requestConfigGetContacts = patch(_requestConfigGetContacts ?? {});
}