//----------------------
// <auto-generated>
//     Generated using the NSwag toolchain v13.20.0.0 (NJsonSchema v11.0.0.0 (Newtonsoft.Json v13.0.0.0)) (http://NSwag.org)
// </auto-generated>
//----------------------

/* tslint:disable */
/* eslint-disable */
// ReSharper disable InconsistentNaming
import * as Types from '../axios-client';
import { useQuery, useMutation } from '@tanstack/react-query';
import type { UseQueryResult, QueryFunctionContext, UseQueryOptions, QueryClient, QueryKey, MutationKey, UseMutationOptions, UseMutationResult, QueryMeta, MutationMeta } from '@tanstack/react-query';
import { trimArrayEnd, isParameterObject, getBaseUrl, addMetaToOptions } from './helpers';
import type { QueryMetaContextValue } from 'react-query-swagger';
import { QueryMetaContext } from 'react-query-swagger';
import { useContext } from 'react';
import * as Client from './CustomerControllerClient'
export { Client };
import type { AxiosRequestConfig } from 'axios';

export type GetCustomerByIdCustomerControllerQueryParameters = {
  id: string ;
}

export function createUrl(): string {
  let url_ = getBaseUrl() + "/customer/create";
  url_ = url_.replace(/[?&]$/, "");
  return url_;
}

export function createMutationKey(): MutationKey {
  return trimArrayEnd([
      'CustomerControllerClient',
      'create',
    ]);
}

export function useCreateMutation<TContext>(options?: Omit<UseMutationOptions<Types.CreateCustomerDto, unknown, Types.CreateCustomerDto, TContext>, 'mutationKey' | 'mutationFn'>): UseMutationResult<Types.CreateCustomerDto, unknown, Types.CreateCustomerDto, TContext> {
  const key = createMutationKey();
  
  const metaContext = useContext(QueryMetaContext);
  options = addMetaToOptions(options, metaContext);
  
  return useMutation({
    ...options,
    mutationFn: (body: Types.CreateCustomerDto) => Client.create(body),
    mutationKey: key,
  });
}
  
export function getCustomerByIdUrl(id: string): string {
  let url_ = getBaseUrl() + "/customer/getCustomerById/{id}";
if (id === undefined || id === null)
  throw new Error("The parameter 'id' must be defined.");
url_ = url_.replace("{id}", encodeURIComponent("" + id));
  url_ = url_.replace(/[?&]$/, "");
  return url_;
}

let getCustomerByIdDefaultOptions: Omit<UseQueryOptions<void, unknown, void>, 'queryKey' | 'queryFn'> & Partial<Pick<UseQueryOptions<void, unknown, void>, 'queryFn'>> = {
};
export function getGetCustomerByIdDefaultOptions() {
  return getCustomerByIdDefaultOptions;
};
export function setGetCustomerByIdDefaultOptions(options: typeof getCustomerByIdDefaultOptions) {
  getCustomerByIdDefaultOptions = options;
}

export function getCustomerByIdQueryKey(id: string): QueryKey;
export function getCustomerByIdQueryKey(...params: any[]): QueryKey {
  if (params.length === 1 && isParameterObject(params[0])) {
    const { id,  } = params[0] as GetCustomerByIdCustomerControllerQueryParameters;

    return trimArrayEnd([
        'CustomerControllerClient',
        'getCustomerById',
        id as any,
      ]);
  } else {
    return trimArrayEnd([
        'CustomerControllerClient',
        'getCustomerById',
        ...params
      ]);
  }
}
export function __getCustomerById(context: QueryFunctionContext, axiosConfig?: AxiosRequestConfig | undefined) {
  return Client.getCustomerById(
      context.queryKey[2] as string,axiosConfig    );
}

export function useGetCustomerByIdQuery<TSelectData = void, TError = unknown>(dto: GetCustomerByIdCustomerControllerQueryParameters, options?: Omit<UseQueryOptions<void, TError, TSelectData>, 'queryKey'>, axiosConfig?: Partial<AxiosRequestConfig>): UseQueryResult<TSelectData, TError>;

export function useGetCustomerByIdQuery<TSelectData = void, TError = unknown>(id: string, options?: Omit<UseQueryOptions<void, TError, TSelectData>, 'queryKey'>, axiosConfig?: Partial<AxiosRequestConfig>): UseQueryResult<TSelectData, TError>;
export function useGetCustomerByIdQuery<TSelectData = void, TError = unknown>(...params: any []): UseQueryResult<TSelectData, TError> {
  let options: UseQueryOptions<void, TError, TSelectData> | undefined = undefined;
  let axiosConfig: AxiosRequestConfig |undefined = undefined;
  let id: any = undefined;
  
  if (params.length > 0) {
    if (isParameterObject(params[0])) {
      ({ id,  } = params[0] as GetCustomerByIdCustomerControllerQueryParameters);
      options = params[1];
      axiosConfig = params[2];
    } else {
      [id, options, axiosConfig] = params;
    }
  }

  const metaContext = useContext(QueryMetaContext);
  options = addMetaToOptions(options, metaContext);

  return useQuery<void, TError, TSelectData>({
    queryFn: axiosConfig ? (context) => __getCustomerById(context, axiosConfig) : __getCustomerById,
    queryKey: getCustomerByIdQueryKey(id),
    ...getCustomerByIdDefaultOptions as unknown as Omit<UseQueryOptions<void, TError, TSelectData>, 'queryKey'>,
    ...options,
  });
}

export function setGetCustomerByIdData(queryClient: QueryClient, updater: (data: void | undefined) => void, id: string) {
  queryClient.setQueryData(getCustomerByIdQueryKey(id),
    updater
  );
}

export function setGetCustomerByIdDataByQueryId(queryClient: QueryClient, queryKey: QueryKey, updater: (data: void | undefined) => void) {
  queryClient.setQueryData(queryKey, updater);
}