//----------------------
// <auto-generated>
//     Generated using the NSwag toolchain v13.20.0.0 (NJsonSchema v11.0.0.0 (Newtonsoft.Json v13.0.0.0)) (http://NSwag.org)
// </auto-generated>
//----------------------

/* tslint:disable */
/* eslint-disable */
// ReSharper disable InconsistentNaming
import * as Types from '../axios-client';
import { useQuery, useMutation } from '@tanstack/react-query';
import type { UseQueryResult, QueryFunctionContext, UseQueryOptions, QueryClient, QueryKey, MutationKey, UseMutationOptions, UseMutationResult, QueryMeta, MutationMeta } from '@tanstack/react-query';
import { trimArrayEnd, isParameterObject, getBaseUrl, addMetaToOptions } from './helpers';
import type { QueryMetaContextValue } from 'react-query-swagger';
import { QueryMetaContext } from 'react-query-swagger';
import { useContext } from 'react';
import * as Client from './StaticControllerClient'
export { Client };
import type { AxiosRequestConfig } from 'axios';

export function getStaticDataUrl(): string {
  let url_ = getBaseUrl() + "/static/getStaticData";
  url_ = url_.replace(/[?&]$/, "");
  return url_;
}

let getStaticDataDefaultOptions: Omit<UseQueryOptions<void, unknown, void>, 'queryKey' | 'queryFn'> & Partial<Pick<UseQueryOptions<void, unknown, void>, 'queryFn'>> = {
};
export function getGetStaticDataDefaultOptions() {
  return getStaticDataDefaultOptions;
};
export function setGetStaticDataDefaultOptions(options: typeof getStaticDataDefaultOptions) {
  getStaticDataDefaultOptions = options;
}

export function getStaticDataQueryKey(): QueryKey;
export function getStaticDataQueryKey(...params: any[]): QueryKey {
  return trimArrayEnd([
      'StaticControllerClient',
      'getStaticData',
    ]);
}
export function __getStaticData(context: QueryFunctionContext, axiosConfig?: AxiosRequestConfig | undefined) {
  return Client.getStaticData(
axiosConfig    );
}

export function useGetStaticDataQuery<TSelectData = void, TError = unknown>(options?: Omit<UseQueryOptions<void, TError, TSelectData>, 'queryKey'>, axiosConfig?: Partial<AxiosRequestConfig>): UseQueryResult<TSelectData, TError>;
export function useGetStaticDataQuery<TSelectData = void, TError = unknown>(...params: any []): UseQueryResult<TSelectData, TError> {
  let options: UseQueryOptions<void, TError, TSelectData> | undefined = undefined;
  let axiosConfig: AxiosRequestConfig |undefined = undefined;
  

  options = params[0] as any;
  axiosConfig = params[1] as any;

  const metaContext = useContext(QueryMetaContext);
  options = addMetaToOptions(options, metaContext);

  return useQuery<void, TError, TSelectData>({
    queryFn: axiosConfig ? (context) => __getStaticData(context, axiosConfig) : __getStaticData,
    queryKey: getStaticDataQueryKey(),
    ...getStaticDataDefaultOptions as unknown as Omit<UseQueryOptions<void, TError, TSelectData>, 'queryKey'>,
    ...options,
  });
}

export function setGetStaticDataData(queryClient: QueryClient, updater: (data: void | undefined) => void, ) {
  queryClient.setQueryData(getStaticDataQueryKey(),
    updater
  );
}

export function setGetStaticDataDataByQueryId(queryClient: QueryClient, queryKey: QueryKey, updater: (data: void | undefined) => void) {
  queryClient.setQueryData(queryKey, updater);
}