//----------------------
// <auto-generated>
//     Generated using the NSwag toolchain v13.20.0.0 (NJsonSchema v11.0.0.0 (Newtonsoft.Json v13.0.0.0)) (http://NSwag.org)
// </auto-generated>
//----------------------

/* tslint:disable */
/* eslint-disable */
// ReSharper disable InconsistentNaming
import * as Types from '../axios-client';
import { useQuery, useMutation } from '@tanstack/react-query';
import type { UseQueryResult, QueryFunctionContext, UseQueryOptions, QueryClient, QueryKey, MutationKey, UseMutationOptions, UseMutationResult, QueryMeta, MutationMeta } from '@tanstack/react-query';
import { trimArrayEnd, isParameterObject, getBaseUrl, addMetaToOptions } from './helpers';
import type { QueryMetaContextValue } from 'react-query-swagger';
import { QueryMetaContext } from 'react-query-swagger';
import { useContext } from 'react';
import { UsersControllerClient as UsersControllerClientClass } from '../axios-client';
import { createClient, getClientFactory } from './helpers';

export const Client = () => getClientFactory()(UsersControllerClientClass);
import type { AxiosRequestConfig } from 'axios';


export function addUserUrl(): string {
  let url_ = getBaseUrl() + "/users/createUser";
  url_ = url_.replace(/[?&]$/, "");
  return url_;
}

export function addUserMutationKey(): MutationKey {
  return trimArrayEnd([
      'UsersControllerClient',
      'addUser',
    ]);
}

export function useAddUserMutation<TContext>(options?: Omit<UseMutationOptions<void, unknown, Types.CreateUserRequestDto, TContext>, 'mutationKey' | 'mutationFn'>): UseMutationResult<void, unknown, Types.CreateUserRequestDto, TContext> {
  const key = addUserMutationKey();
  
  const metaContext = useContext(QueryMetaContext);
  options = addMetaToOptions(options, metaContext);
  
  return useMutation({
    ...options,
    mutationFn: (body: Types.CreateUserRequestDto) => Client().addUser(body),
    mutationKey: key,
  });
}
  
export function getUsersUrl(): string {
  let url_ = getBaseUrl() + "/users/get";
  url_ = url_.replace(/[?&]$/, "");
  return url_;
}

export function getUsersMutationKey(): MutationKey {
  return trimArrayEnd([
      'UsersControllerClient',
      'getUsers',
    ]);
}

export function useGetUsersMutation<TContext>(options?: Omit<UseMutationOptions<Types.UserPaginationResponse, unknown, Types.GetUserRequestDto, TContext>, 'mutationKey' | 'mutationFn'>): UseMutationResult<Types.UserPaginationResponse, unknown, Types.GetUserRequestDto, TContext> {
  const key = getUsersMutationKey();
  
  const metaContext = useContext(QueryMetaContext);
  options = addMetaToOptions(options, metaContext);
  
  return useMutation({
    ...options,
    mutationFn: (body: Types.GetUserRequestDto) => Client().getUsers(body),
    mutationKey: key,
  });
}